This is for stalk deployment

version: '3.6'
services:
  app: 
    image: nginx
    ports:
      - "80:80"
    deploy:
      replicas: 2
  web: 
    image: httpd
    ports:
      - "8081:80"
    deploy:
      replicas: 6
